name: Build UI

on:
  push:
    paths-ignore:
      - "aleph/**"
      - "contrib/**"
      - "helm/**"
      - "mappings/**"
      - "site/**"
      - "docs/**"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: echo "ALEPH_SECRET=batman\n" >> aleph.env

      - name: Build development image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui:${{ github.sha } ui
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui:${{ github.sha } ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui:latest

      - name: Check code formatting
        run: make format-check-ui

      - name: Run linter
        run: make lint-ui

      - name: Run tests
        run: make test-ui

      - name: Build production image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui-production:${{ github.sha } -f ui/Dockerfile.production ui

      - name: Push docker image (hash)
        env:
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        if: env.GITHUB_PASSWORD != null
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui-production:${{ github.sha }

      - name: Push docker image (tagged)
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          export ALEPH_TAG=${{ GITHUB_REF/refs\/tags\// }}
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui-production:${{ github.sha } ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui-production:${{ ALEPH_TAG }};
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui-production:${{ ALEPH_TAG }};
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui-production:${{ github.sha } ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui-production:latest;
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui-production:latest;
